<%@ Page Title="Students" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Students.aspx.cs" Inherits="SomeUniversity.Students" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <br />
    <asp:HyperLink NavigateUrl="~/AddStudent" Text="Add New Student" runat="server" class="btn btn-primary"/>
    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
    <br />
    <br />  
    <asp:GridView runat="server" ID="studentsGrid" ItemType="SomeUniversity.Models.Student" DataKeyNames="StudentID" 
        SelectMethod="studentsGrid_GetData" 
        UpdateMethod="studentsGrid_UpdateItem" AutoGenerateEditButton="true"
        DeleteMethod="studentsGrid_DeleteItem" AutoGenerateDeleteButton="true"
        AutoGenerateColumns="false">
        <Columns>
            <asp:DynamicField DataField="StudentID" />
            <asp:DynamicField DataField="LastName" />
            <asp:DynamicField DataField="FirstName" />
            <asp:DynamicField DataField="Year" />          
            <asp:TemplateField HeaderText="Total Credits">
              <ItemTemplate>
                <asp:Label Text="<%# Item.Enrollments.Sum(en => en.Course.Credits) %>" 
                    runat="server" />
              </ItemTemplate>
            </asp:TemplateField>        
        </Columns>
    </asp:GridView>
</asp:Content>
