<%@ Page Title="Students" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Students.aspx.cs" Inherits="SomeUniversity.Students" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <br />
    <br />
    <div class="row">
        <div class="col-sm-1">
            <p class="h4">Show</p>
        </div>
        <div class="col-sm-2">
            <asp:DropDownList runat="server" AutoPostBack="true" ID="DisplayYear" class="form-control">
                <asp:ListItem Text="All" Value="" />
                <asp:ListItem Text="Freshman" />
                <asp:ListItem Text="Sophomore" />
                <asp:ListItem Text="Junior" />
                <asp:ListItem Text="Senior" />
            </asp:DropDownList>
        </div>
        <div class="col-sm-3 col-sm-offset-6 text-right">
            <a href="~/AddStudent" runat="server" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-plus"></span> &nbsp; &nbsp;Add New student
            </a>
        </div>
    </div>
  
    <asp:ValidationSummary runat="server" ShowModelStateErrors="true"/>
    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
    <br />
   
    <asp:GridView runat="server" ID="studentsGrid" ItemType="SomeUniversity.Models.Student" DataKeyNames="StudentID" 
        SelectMethod="studentsGrid_GetData" 
        UpdateMethod="studentsGrid_UpdateItem" AutoGenerateEditButton="True"
        DeleteMethod="studentsGrid_DeleteItem" AutoGenerateDeleteButton="True"
        AutoGenerateColumns="false"
        AllowSorting="true"
        AllowPaging="true" PageSize="12"
         BorderColor="White" BorderStyle="Dotted" CssClass="table table-striped" GridLines="None">
        <Columns>
            <asp:DynamicField DataField="StudentID"/>
            <asp:DynamicField DataField="FirstName" />
            <asp:DynamicField DataField="LastName" />
            <asp:DynamicField DataField="Year" />          
            <asp:TemplateField HeaderText="Total Credits">
              <ItemTemplate>
                <asp:Label Text="<%# Item.Enrollments.Sum(en => en.Course.Credits) %>" 
                    runat="server" />
              </ItemTemplate>
            </asp:TemplateField>        
        </Columns>
        <PagerSettings Mode="NumericFirstLast" />
    </asp:GridView>
</asp:Content>
