<%@ Page Title="Product Admin" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AdminProduct.aspx.cs" Inherits="RGN.Admin.AdminProduct" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <br />
    <br />
    <div class="container">
        <br />
        <h2>Product Administration</h2>
        <br />
        <div class="text-right">
            <a href="AddNewProduct" class="btn btn-info btn-sm">Add New Product</a>
        </div>
        <br />
        <asp:GridView runat="server" ID="categoryGrid" ItemType="RGN.Models.Product" DataKeyNames="ProductID" 
            SelectMethod="GetProducts"  AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            UpdateMethod="UpdateProduct" DeleteMethod="DeleteProduct" 
            AutoGenerateColumns="False" AllowSorting="True"
            BorderColor="White" BorderStyle="Dotted" CssClass="table table-striped" GridLines="None">
                <Columns>
                    <asp:DynamicField DataField="ProductName"/>
                    <asp:DynamicField DataField="CategoryID"/>
                    <asp:DynamicField DataField="UnitPrice"/>
                    <asp:DynamicField DataField="Description"/>
                </Columns>
        </asp:GridView>
    </div>
</asp:Content>
